//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBKArlGoja
{
    using System;
    using System.Collections.Generic;
    
    public partial class C666
    {
        public int IdClientServise { get; set; }
        public int IdClient { get; set; }
        public System.DateTime TimeStart { get; set; }
        public int DurationSeconds { get; set; }
        public int Expr1 { get; set; }
        public int IdService { get; set; }
        public int IdServise { get; set; }
    }
}
