//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBKArlGoja
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienView
    {
        public int IdClient { get; set; }
        public string FName { get; set; }
        public string SName { get; set; }
        public string PName { get; set; }
        public System.DateTime BthDate { get; set; }
        public string Email { get; set; }
        public System.DateTime RegDate { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> maxDate { get; set; }
        public Nullable<int> Counts { get; set; }
    }
}
