//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBKArlGoja
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientServicePhoto
    {
        public int IdClientServicePhoto { get; set; }
        public int IdClientService { get; set; }
        public string PhotoPath { get; set; }
    
        public virtual ClientServise ClientServise { get; set; }
    }
}
