//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBKArlGoja
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientServise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientServise()
        {
            this.ClientServicePhoto = new HashSet<ClientServicePhoto>();
        }
    
        public int IdClientServise { get; set; }
        public int IdClient { get; set; }
        public int IdService { get; set; }
        public System.DateTime TimeStart { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientServicePhoto> ClientServicePhoto { get; set; }
        public virtual Service Service { get; set; }
    }
}
