//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBKArlGoja
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_clientDetails
    {
        public string ФИО { get; set; }
        public Nullable<int> AGE { get; set; }
        public Nullable<System.DateTime> Дата_приема { get; set; }
        public string Пол { get; set; }
        public Nullable<int> тэг_ { get; set; }
    }
}
